* =Btce= Module

This is a library in Ruby to easily acces the data provided by the [[http://btc-e.com][btc-e.com]] API.
It was originally being used on [[http://btc-charts.com][BTC-Charts.com]], among other places.
It is available under a BSD-style license.

** Installation

The library is available as a rubygem.

#+BEGIN_SRC sh
gem install btce
#+END_SRC

** Basic Usage

Populate the file =btce-api-key.yml= along the same lines as the example.

The only thing that 99% of the people using the library will want to do with it:

#+BEGIN_SRC ruby
require 'btce'
ticker = Btce::Ticker.new "btc_usd"
#+END_SRC

This should return something resembling:

#+BEGIN_SRC ruby
#<Btce::Ticker:0x00000000d5d9a0 @operation="ticker",
                                @pair="btc_usd",
                                @json={"ticker"=>{"high"=>127,
                                                  "low"=>87.301,
                                                  "avg"=>107.1505,
                                                  "vol"=>4240695.81634,
                                                  "vol_cur"=>39298.55663,
                                                  "last"=>115,
                                                  "buy"=>115,
                                                  "sell"=>114.499,
                                                  "server_time"=>1366406293}}>
#+END_SRC

You can then acces the fields with the predefined methods of the =Ticker= class.

** =API= Class

This is the parent class for both the =PublicAPI= class and the =TradeAPI= class.

*** =BTCE_DOMAIN=

This is the domain of the server, defaulting to the string =btc-e.com=.

*** =CURRENCIES=

This is a list of the short strings for all of the currencies currently supported on [[http://btc-e.com][btc-e.com]].

*** =CURRENCY_PAIRS=

This is a list of all of the supported currency pairs on [[http://btc-e.com][btc-e.com]].

*** =MAX_DIGITS=

This indicates how many digits past the decimal place are commonly displayed to humans for a given currency pair.

*** Class Methods

**** =get_https=

**** =get_json=

** =PublicAPI= Class

*** =OPERATIONS=

*** Class Methods

**** =get_pair_operation_json=

**** =get_pair_fee_json=

**** =get_pair_ticker_json=

**** =get_pair_trades_json=

**** =get_pair_depth_json=

**** get_<PAIR>_fee_json

**** get_<PAIR>_ticker_json

**** get_<PAIR>_trades_json

**** get_<PAIR>_depth_json


** =PublicOperation= Class

** =Fee= Class

*** Instance Methods

**** =trade=

** =Ticker= Class

*** Instance Methods

**** =high=

**** =low=

**** =avg=, =average=

**** =vol=, =volume=

**** =vol_cur=

**** =last=

**** =buy=

**** =sell=

**** =server_time=

** =Trade= Class

*** Instance Methods

**** =date=

**** =price=

**** =amount=

**** =tid=

**** =price_currency=

**** =item=

**** =trade_type=

** =Trades= Class

** =Depth= Class

** =TradeAPI= Class

*** Class Methods

**** =sign=

**** =trade_api_call=

**** =get_info=

**** =trade_history=

**** =trans_history=

**** =trade=

**** =order_list=

**** =cancel_order=
